#!/bin/sh
#
# CIP Core, generic profile
#
# Copyright (c) Siemens AG, 2025
#
# Authors:
#  Quirin Gylstorff <quirin.gylstorff@siemens.com>
#
. /usr/share/factory-reset/reset-env
target_devices="${INITRAMFS_FACTORY_RESET_DEVICES}"

if /usr/sbin/get-factory-reset.sh --delete | grep -q "factory-reset"; then
    log_begin_msg "Factory Reset"
    for target in ${target_devices}; do
        log_begin_msg "Reset device: $target"
        fs_type=$(get_fstype "${target}")
        case "$target" in
            *by-partlabel*)
                label="$(basename "${target}" )"
                ;;
            *)
                label=$(blkid --match-tag LABEL "$target" | awk -F= '{gsub(/"/,"");print $2}' )
                if [ -z "${label}" ]; then
                    log_warning_msg "Could not find any label  for target '$target'"
                fi
                ;;
        esac
        if [ "$fs_type" = "luks" ]; then
            target=$(find /dev/mapper -iname "*$label")
            fs_type=$(get_fstype "${target}")
            echo "luks device detected use $target"
        fi
        case ${fs_type} in
            ext*)
                /sbin/mke2fs -L "${label}" -F -t ext4 "${target}"
                ;;
            btrfs)
                /sbin/mkfs.btrfs -L "${label}" --force "${target}"
                ;;
            *)
                log_warning_msg "Unrecognized filesystem type ${fs_type} - could not format"
                ;;
        esac
        log_end_msg "Reset device: $target"
    done
    log_end_msg "Factory Reset"
fi
