#
# CIP Core, generic profile
#
# Copyright (c) Siemens AG, 2019-2025
#
# SPDX-License-Identifier: MIT
#

DISTRO_ARCH = "armhf"
DTB_FILES = "am335x-boneblack.dtb"

IMAGE_FSTYPES ?= "wic"
IMAGER_INSTALL:wic += "u-boot-bbb ${SYSTEMD_BOOTLOADER_INSTALL}"
IMAGER_BUILD_DEPS += "u-boot-bbb"

USE_CIP_KERNEL_CONFIG = "1"
KERNEL_DEFCONFIG = "cip-kernel-config/${KERNEL_DEFCONFIG_VERSION}/arm/cip_merged_defconfig"

# for SWUpdate setups: watchdog is configured in U-Boot
WDOG_TIMEOUT = "0"
