#
# Copyright (c) Texas Instruments Incorporated, 2025
#
# Authors:
#  Sai Sree Kartheek Adivi <s-adivi@ti.com>
#
# SPDX-License-Identifier: MIT
#

DISTRO_ARCH = "arm64"
DTB_FILES = "k3-am62p5-sk.dtb"

IMAGE_FSTYPES ?= "wic"

IMAGER_INSTALL:wic += "${SYSTEMD_BOOTLOADER_INSTALL} u-boot-ti-am62px-sk"
IMAGER_BUILD_DEPS += "u-boot-ti-am62px-sk"

IMAGE_PREINSTALL += "firmware-ti-connectivity"

IMAGE_BOOT_FILES = " \
    /usr/lib/u-boot/${MACHINE}/u-boot.img;u-boot.img \
    /usr/lib/u-boot/${MACHINE}/tispl.bin;tispl.bin \
    /usr/lib/u-boot/${MACHINE}/tiboot3-am62px-hs-fs-evm.bin;tiboot3.bin"

USE_CIP_KERNEL_CONFIG = "1"
KERNEL_DEFCONFIG = "cip-kernel-config/${KERNEL_DEFCONFIG_VERSION}/arm64/ti_defconfig"

WDOG_TIMEOUT = "0"
