#
# CIP Core, generic profile
#
# Copyright (c) Toshiba Corporation, 2026
#
# Authors:
#  Shivanand Kunijadar <Shivanand.Kunijadar@toshiba-tsip.com>
#
# SPDX-License-Identifier: MIT
#

require conf/distro/debian-sid.conf
require cip-core-common.inc
