#
# CIP Core, generic profile
#
# Copyright (c) Siemens AG, 2024-2025
#
# Authors:
#  Cedric Hombourger <cedric.hombourger@siemens.com>
#
# SPDX-License-Identifier: MIT
#

require conf/distro/debian-trixie.conf
require cip-core-common.inc
