#!/bin/sh
#
# CIP Core, generic profile
#
# Copyright (c) Siemens AG, 2020-2022
#
# Authors:
#  Jan Kiszka <jan.kiszka@siemens.com>
#
# SPDX-License-Identifier: MIT

prereqs()
{
    # Make sure that this script is run last in local-top
    # If the script cryptroot is installed this script
    # should be second to last
    local req
    for req in "${0%/*}"/*; do
        script="${req##*/}"
        if [ "$script" != "${0##*/}" ] && [ "$script" != "cryptroot" ]; then
            printf '%s\n' "$script"
        fi
    done
}
case $1 in
prereqs)
    prereqs
    exit 0
    ;;
esac

. /scripts/functions

. /scripts/cip-initramfs-functions

load_abrootfs_env_from_cmdline()
{
    abrootfs_opts=$(cat /proc/cmdline | sed -n 's/.*cip.abrootfs_root_options=\([^ ]*\).*/\1/p' | sed 's/,/ /g')
    for opt in $abrootfs_opts; do
        key=$(echo $opt | sed 's/=.*//')
        val=$(echo $opt | sed 's/^[^=]*=//')
        case "$key" in
            target-image-uuid)
                TARGET_IMAGE_UUID="$val"
                ;;
            *)
                ;;
        esac
    done
}

found_root=""
scanned_partitions=""

find_root_via_image_uuid()
{
    loc_partitions="$1"
    for part in $loc_partitions; do
        if [ "$(blkid -p "${part}" --match-types novfat -s USAGE -o value)" = "filesystem" ]; then
            mount -o ro -t "$(get_fstype "${part}")" "${part}" "${rootmnt}"
            if [ -e "${rootmnt}/etc/os-release" ]; then
                . "${rootmnt}/etc/os-release"
            fi
            umount "${rootmnt}"
            if [ -n "${IMAGE_UUID}" ] && [ -n "${TARGET_IMAGE_UUID}" ] &&
                   [ "${IMAGE_UUID}" = "${TARGET_IMAGE_UUID}" ]; then
                found_root="${part}"
                break
            fi
        fi
    done
}

# Even if this script fails horribly, make sure there won't be a chance the
# current $ROOT will be attempted.  As this device most likely contains a
# perfectly valid filesystem, it would be mounted successfully, leading to a
# broken boot.
echo "ROOT=/dev/null" >/conf/param.conf
wait_for_udev 10

load_abrootfs_env_from_cmdline

case "$ROOT" in
    PART*)
        # Root was given as PARTUUID= or PARTLABEL=.
        # Use blkid to find the matching partition
        found_root=$(blkid --list-one --output device --match-token "$ROOT")
        if [ -z "${found_root}" ]; then
            log_begin_msg "Waiting for ${ROOT}"
            wait_30sec_for_condition find_root_by_part
        fi
        ;;
    "")
        # No Root device was given. Search for the matching IMAGE_UUID
        partitions="$(blkid -o device)"
        find_root_via_image_uuid "$partitions"
        if [ -z "${found_root}" ]; then
            log_begin_msg "Waiting for IMAGE_UUID=${TARGET_IMAGE_UUID}"
            scanned_partitions="${partitions}"
            wait_30sec_for_condition scan_for_partitions
        fi
        ;;
esac

if [ -z "${found_root}" ]; then
    panic "Can't find the root device with matching UUID!"
fi

ROOT="${found_root}"
echo "ROOT=${ROOT}" >/conf/param.conf
