#
# CIP Core, generic profile
#
# Copyright (c) Toshiba Corporation, 2020
#
# Authors:
#  Venkata Pyla <venkata.pyla@toshiba-tsip.com>
#
# SPDX-License-Identifier: MIT
#
header:
  version: 14
  includes:
   - kas/opt/encrypt-data.yml
   - kas/opt/ebg-secure-boot-snakeoil.yml

target: cip-core-image-security

# (Warning) CIP users are strongly recommended not to use CIP default credentials for production images.
local_conf_header:
  root_password: |
    USERS += "root"
    USER_root[password] = "CIPsecurity@123"
    USER_root[flags] = "clear-text-password"
  security-override: |
    OVERRIDES .= ":security"
